### ISSUE TITLE
Provide test/verification cases

### ISSUE THREAD

**Issue by cephid13** [bbercovici/SBGAT#46]
Show results for various standard shape models of different resolutions to verify consistency and correctness. As we did when troubleshooting code with increasing the resolution of the box shape model - can compare against an analytical solution. Could also use an ellipsoid.

**Comment by bbercovici** [comment]
Added three tests:
- test_loading_shape(): checks if a provided shape model can be loaded
- test_pgm_consistency_cube(): checks if the PGM acceleration over a cube corresponds to the analytical value, for several cube resolutions
- test_pgm_consistency_ellipsoid(): checks if the PGM acceleration over an ellipsoid is compatible to its analytical value (computed from Scheeres' _Orbital Motion in Strongly Perturbed Environment_, page 66)
